# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main

jobs:
    check-publish-ready:
        uses: ./.github/workflows/run-tests.yml

    publish:
        runs-on: ubuntu-latest
        needs: [check-publish-ready]
        env:
            REACT_APP_NAME: ${{ secrets.APP_NAME }}

        steps:
            - uses: actions/checkout@v4

            - name: ðŸ”Ž Get Package version
              run: |
                  echo "VITE_APP_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1 )" >> $GITHUB_ENV

            - name: ðŸŒ Check Environment Variables
              if: github.ref == 'refs/heads/feature'
              run: |
                  echo "REACT APP VERSION: $VITE_APP_VERSION"

            - name: âš™ï¸ Configure Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://registry.npmjs.org'

            - name: âš™ï¸ Configure NPM
              run: |
                  npm i -g npm@9
                  echo Node Version: `node --version`
                  echo NPM Version: `npm --version`

            - name: ðŸ”¨ Install dependencies and build
              run: npm install && npm run build

            - name: ðŸ“¦ Publish package on NPM
              if: github.ref == 'refs/heads/main'
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

    create-pull-request:
        runs-on: ubuntu-latest
        needs: [publish]

        steps:
            - name: Not currently Running
              run: echo "This workflow is not currently running..."

            # - name: ðŸ’¬ Submit Pull Request on benweare-ts-server
            #   if: github.ref == 'refs/heads/main'
            #   run: |
            #       # Configure and clone
            #       git config --global user.name "${GITHUB_ACTOR}"
            #       git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            #       BRANCH_NAME="CHORE-client-$VITE_APP_VERSION"

            #       git clone https://incendiarybean:${{ secrets.ACCESS_TOKEN }}@github.com/incendiarybean/benweare-ts-server --branch=development
            #       cd benweare-ts-server

            #       # Install latest dependencies and update the client
            #       npm install --quiet
            #       npm install benweare.co.uk-client --quiet

            #       # Commit the changes and push the feature branch to origin
            #       git checkout -b $BRANCH_NAME
            #       git commit -am "CHORE: Bump client to $VITE_APP_VERSION"
            #       git push origin $BRANCH_NAME

            #       # Create a PR on the branch of benweare-ts-server
            #       echo "${{ secrets.ACCESS_TOKEN }}" > token.txt
            #       gh auth login --with-token < token.txt
            #       gh pr create \
            #         --body "AUTOMATED: Bump to $VITE_APP_VERSION" \
            #         --title "CHORE: Bump client to $VITE_APP_VERSION" \
            #         --head "$BRANCH_NAME" \
            #         --base "development"
