# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main
            - '*'
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            REACT_APP_NAME: ${{ secrets.APP_NAME }}

        steps:
            - uses: actions/checkout@v4

            # - name: ğŸ” Get Package version
            #   run: |
            #       echo "REACT_APP_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1 )" >> $GITHUB_ENV

            # - name: ğŸŒ Check Environment Variables
            #   if: github.ref == 'refs/heads/feature'
            #   run: |
            #       echo "REACT APP VERSION: $REACT_APP_VERSION"

            # - name: âš™ï¸ Configure Node.js environment
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '18'
            #       registry-url: 'https://registry.npmjs.org'

            # - name: âš™ï¸ Configure NPM
            #   run: |
            #       npm i -g npm@9
            #       echo Node Version: `node --version`
            #       echo NPM Version: `npm --version`

            # - name: ğŸ”¨ Install dependencies and build
            #   run: npm install && npm run build

            # - name: ğŸ§¼ Run Linter
            #   run: npm run lint

            # - name: ğŸ§ª Run Tests
            #   run: npm test

            # - name: ğŸ“¦ Publish package on NPM
            #   if: github.ref == 'refs/heads/main'
            #   run: npm publish --access public
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

            - name: ğŸ’¬ Submit Pull Request on benweare-ts-server
              run: |
                  git clone https://github.com/incendiarybean/benweare-ts-server.git --branch=development

                  cd benweare-ts-server

                  npm install 
                  npm install benweare.co.uk-client
