# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            REACT_APP_NAME: ${{ secrets.APP_NAME }}

        steps:
            - uses: actions/checkout@v3

            - name: Get Package version ğŸ”
              run: |
                  echo "REACT_APP_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1 )" >> $GITHUB_ENV

            - name: Check Environment Variables ğŸ”
              if: github.ref == 'refs/heads/feature'
              run: |
                  echo "REACT APP VERSION: $REACT_APP_VERSION"

            - name: Setup Node.js environment ğŸ”§
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Update to NPM 8.6.0 âš™ï¸
              run: |
                  npm i -g npm@8.6.0
                  echo Node Version: `node --version`
                  echo NPM Version: `npm --version`

            - name: Install dependencies and build ğŸ”¨
              run: npm install && npm run build

            - name: Run Tests ğŸ§ª
              run: npm test

            - name: Publish package on NPM ğŸ“¦
              if: github.ref == 'refs/heads/main'
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
