# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            REACT_APP_HOSTNAME: ${{ secrets.PROD_HOSTNAME }}
            REACT_APP_LOCAL: ${{ secrets.DEV_HOSTNAME }}
            REACT_APP_SOCKET: ${{ fromJSON('["development", "production"]')[github.ref == 'refs/heads/main'] }}
        steps:
            - uses: actions/checkout@v3

            - name: Environment ‚öôÔ∏è
              run: |
                  echo "REACT SOCKET ENV: $REACT_APP_SOCKET"
                  ls
                  REACT_APP_VERSION=grep '"version"' package.json | cut -d '"' -f 4 | head -n 1
                  echo "REACT SOCKET ENV: $REACT_APP_VERSION"

            - name: Setup Node.js environment üîß
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Update to NPM 8.6.0 ‚öôÔ∏è
              run: |
                  npm i -g npm@8.6.0
                  echo Node Version: `node --version`
                  echo NPM Version: `npm --version`

            - name: Install dependencies and build üî®
              run: npm install && npm run build

            - name: Run Tests üß™
              run: npm test

            - name: Publish package on NPM üì¶
              if: github.ref == 'refs/heads/main'
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
