# This is a basic cypress workflow that is automatically triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_call:
    push:
        branches:
            - "*"
            - "!main"
    pull_request:
        branches:
            - "*"
            - "!main"

jobs:
    lint-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: ğŸ§¼ Run Linter
              run: |
                  npm install --quiet
                  npm run lint

    cypress-test:
        runs-on: ubuntu-latest
        needs: [lint-code]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: ğŸ” Get Package version
              run: |
                  echo "VITE_APP_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1 )" >> $GITHUB_ENV

            - name: ğŸ”¨ Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
                  build: npm run build

            - name: ğŸ’¾ Save build folder
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  if-no-files-found: error
                  path: build

            - name: â¬‡ï¸ Download the build folder
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build

            - name: ğŸ§ª Cypress E2E Test
              uses: cypress-io/github-action@v6
              with:
                  start: npm start

            - name: ğŸ§ª Cypress Component Tests
              uses: cypress-io/github-action@v6
              with:
                  component: true
              env:
                  npm_package_version: ${{ env.VITE_APP_VERSION }}

            - name: â¬†ï¸ Upload Test Recordings
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-videos
                  path: cypress/videos

            - name: â¬†ï¸ Upload Test Failure Screenshots
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
